name: Deploy Frontend

on:
  workflow_dispatch:

jobs:
  Frontend-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: CheckOut Source Code
        uses: actions/checkout@v4
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Set AKS Context
        uses: azure/aks-set-context@v3
        with:
          resource-group: Containers-RG
          cluster-name: aks-practice
      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.11.1
      - name: Frontend Deployment using Helm
        run: |
          helm upgrade --install UI-app ./frontend/charts/frontend \
          --namespace frontend \
          --create-namespace \
          --set image.repository=akspractice49.azurecr.io/frontend \
          --set image.tag=0.0.1
      
